# Generated by Django 6.0.7 on 2026-08-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiReplyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('sent', '已发送'), ('failed', '失败'), ('skipped', '跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('ai_content', models.TextField(blank=True, default='', verbose_name='AI生成回复内容')),
                ('ai_segments', models.JSONField(blank=True, default=list, verbose_name='分段发送内容(模仿真人)')),
                ('prompt_snapshot', models.TextField(blank=True, default='', verbose_name='生成时Prompt快照')),
                ('llm_tokens', models.IntegerField(default=0, verbose_name='消耗token数')),
                ('credit_cost', models.IntegerField(default=0, verbose_name='扣减积分数')),
                ('error', models.TextField(blank=True, default='', verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': 'AI回复任务',
                'verbose_name_plural': 'AI回复任务',
                'db_table': 'mf_ai_reply_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '失败'), ('skipped', '跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('error', models.TextField(blank=True, default='', verbose_name='失败原因')),
                ('monthly_count', models.IntegerField(default=0, verbose_name='该客户本月已收群发数')),
            ],
            options={
                'verbose_name': '群发接收者',
                'verbose_name_plural': '群发接收者',
                'db_table': 'mf_broadcast_recipient',
            },
        ),
        migrations.CreateModel(
            name='BroadcastTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('material_type', models.CharField(choices=[('text', '文本'), ('link', '图文链接'), ('miniprogram', '小程序卡片')], default='text', max_length=20, verbose_name='素材类型')),
                ('material_content', models.JSONField(blank=True, default=dict, verbose_name='素材内容')),
                ('filter_tags', models.JSONField(blank=True, default=list, verbose_name='接收者标签筛选')),
                ('filter_conditions', models.JSONField(blank=True, default=dict, verbose_name='其他筛选条件')),
                ('total_count', models.IntegerField(default=0, verbose_name='计划接收人数')),
                ('sent_count', models.IntegerField(default=0, verbose_name='已发送数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待发送'), ('sending', '发送中'), ('completed', '已完成'), ('paused', '已暂停')], default='draft', max_length=20, verbose_name='状态')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='定时发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '群发任务',
                'verbose_name_plural': '群发任务',
                'db_table': 'mf_broadcast_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(blank=True, default='', max_length=100, verbose_name='绑定智能体agent_id')),
                ('ai_enabled', models.BooleanField(default=True, verbose_name='企业级AI总开关')),
                ('reply_style', models.CharField(choices=[('professional', '专业'), ('friendly', '友好'), ('lively', '活泼'), ('calm', '沉稳')], default='friendly', max_length=20, verbose_name='回复风格')),
                ('reply_length', models.CharField(choices=[('short', '简短'), ('medium', '适中'), ('detailed', '详细')], default='short', max_length=20, verbose_name='回复长度')),
                ('customer_address', models.CharField(choices=[('remark', '备注名'), ('nickname', '昵称'), ('surname_prefix', '姓+称谓')], default='remark', max_length=20, verbose_name='客户称呼方式')),
                ('ai_signature', models.BooleanField(default=False, verbose_name='AI回复是否附加签名')),
                ('quick_replies', models.JSONField(blank=True, default=list, verbose_name='话术库(快捷回复模板)')),
                ('forbidden_words', models.JSONField(blank=True, default=list, verbose_name='禁用词列表')),
                ('work_hours_start', models.TimeField(blank=True, null=True, verbose_name='AI工作时间开始')),
                ('work_hours_end', models.TimeField(blank=True, null=True, verbose_name='AI工作时间结束')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '聊天设置',
                'verbose_name_plural': '聊天设置',
                'db_table': 'mf_chat_setting',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_id', models.CharField(blank=True, default='', max_length=100, verbose_name='统一社会信用代码')),
                ('customer_level', models.CharField(choices=[('VIP', 'VIP'), ('A', 'A级'), ('B', 'B级'), ('C', 'C级')], default='C', max_length=20, verbose_name='客户等级')),
                ('total_orders', models.IntegerField(default=0, verbose_name='历史订单数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='历史采购总额')),
                ('last_order_at', models.DateTimeField(blank=True, null=True, verbose_name='最后下单时间')),
                ('browse_products', models.JSONField(blank=True, default=list, verbose_name='常浏览产品列表')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='自动标签')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='画像更新时间')),
            ],
            options={
                'verbose_name': '客户画像',
                'verbose_name_plural': '客户画像',
                'db_table': 'mf_customer_profile',
            },
        ),
        migrations.CreateModel(
            name='MomentsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', verbose_name='朋友圈文案')),
                ('media_files', models.JSONField(blank=True, default=list, verbose_name='图片/视频文件列表')),
                ('visible_tags', models.JSONField(blank=True, default=list, verbose_name='可见标签')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('sent', '已发送'), ('failed', '失败')], default='draft', max_length=20, verbose_name='状态')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='定时发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '朋友圈任务',
                'verbose_name_plural': '朋友圈任务',
                'db_table': 'mf_moments_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProactiveFollowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('event', '事件触发'), ('schedule', '定时触发'), ('manual', '手动触发')], default='event', max_length=20, verbose_name='触发类型')),
                ('trigger_event', models.JSONField(blank=True, default=dict, verbose_name='触发事件数据')),
                ('agent_id', models.CharField(blank=True, default='', max_length=100, verbose_name='使用的智能体')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '失败'), ('skipped', '跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('ai_content', models.TextField(blank=True, default='', verbose_name='AI生成开场白')),
                ('error', models.TextField(blank=True, default='', verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '主动跟进任务',
                'verbose_name_plural': '主动跟进任务',
                'db_table': 'mf_proactive_follow_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
