# Generated by Django 6.0.7 on 2026-08-01 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing_follow', '0001_initial'),
        ('platform', '0018_expand_prompt_category'),
        ('wecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireplytask',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reply_tasks', to='wecom.wecomcontact', verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='aireplytask',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reply_tasks', to='wecom.wecomdevice', verbose_name='企微设备'),
        ),
        migrations.AddField(
            model_name='aireplytask',
            name='inbound_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_tasks', to='wecom.wecommessage', verbose_name='触发消息'),
        ),
        migrations.AddField(
            model_name='aireplytask',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reply_tasks', to='platform.tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='broadcastrecipient',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_recipients', to='wecom.wecomcontact', verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='broadcasttask',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_tasks', to='wecom.wecomdevice', verbose_name='企微设备'),
        ),
        migrations.AddField(
            model_name='broadcasttask',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_tasks', to='platform.tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='broadcastrecipient',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='marketing_follow.broadcasttask', verbose_name='群发任务'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to='wecom.wecomdevice', verbose_name='企微设备'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to='platform.tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='wecom.wecomcontact', verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to='platform.tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='momentstask',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments_tasks', to='wecom.wecomdevice', verbose_name='企微设备'),
        ),
        migrations.AddField(
            model_name='momentstask',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments_tasks', to='platform.tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='proactivefollowtask',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_follow_tasks', to='wecom.wecomcontact', verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='proactivefollowtask',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_follow_tasks', to='wecom.wecomdevice', verbose_name='企微设备'),
        ),
        migrations.AddField(
            model_name='proactivefollowtask',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_follow_tasks', to='platform.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastrecipient',
            unique_together={('task', 'contact')},
        ),
        migrations.AlterUniqueTogether(
            name='chatsetting',
            unique_together={('tenant', 'device')},
        ),
    ]
