# Generated by Django 6.0.7 on 2026-08-01 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_follow', '0002_initial'),
        ('platform', '0018_expand_prompt_category'),
        ('wecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('trigger_type', models.CharField(choices=[('event', '事件触发'), ('schedule', '定时触发'), ('manual', '手动触发')], default='event', max_length=20, verbose_name='触发类型')),
                ('trigger_config', models.JSONField(blank=True, default=dict, verbose_name='触发条件配置')),
                ('action_type', models.CharField(choices=[('proactive_follow', '主动跟进'), ('broadcast', '精准群发'), ('moments', '朋友圈')], default='proactive_follow', max_length=20, verbose_name='动作类型')),
                ('action_config', models.JSONField(blank=True, default=dict, verbose_name='动作配置')),
                ('agent_id', models.CharField(blank=True, default='', max_length=100, verbose_name='绑定智能体agent_id')),
                ('status', models.CharField(choices=[('active', '运行中'), ('paused', '已暂停'), ('expired', '已过期')], default='active', max_length=20, verbose_name='任务状态')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='生效开始时间')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='生效结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_tasks', to='wecom.wecomdevice', verbose_name='企微设备')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_tasks', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '营销自动化任务',
                'verbose_name_plural': '营销自动化任务',
                'db_table': 'mf_marketing_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('skipped', '跳过')], default='pending', max_length=20, verbose_name='执行状态')),
                ('trigger_event', models.JSONField(blank=True, default=dict, verbose_name='触发事件数据')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('error', models.TextField(blank=True, default='', verbose_name='失败原因')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始执行时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('target_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='wecom.wecomcontact', verbose_name='目标联系人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='marketing_follow.marketingtask', verbose_name='关联任务')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '任务执行记录',
                'verbose_name_plural': '任务执行记录',
                'db_table': 'mf_task_execution',
                'ordering': ['-created_at'],
            },
        ),
    ]
