# Generated by Django 6.0.7 on 2026-08-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_follow', '0003_marketingtask_taskexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsetting',
            name='group_fixed_reply_enabled',
            field=models.BooleanField(default=False, help_text='开启后在固定时间段内自动回复群消息', verbose_name='群聊固定回复开关'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='group_fixed_reply_end',
            field=models.TimeField(blank=True, null=True, verbose_name='群聊固定回复结束时间'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='group_fixed_reply_rooms',
            field=models.JSONField(blank=True, default=list, help_text='固定回复功能生效的群ID列表', verbose_name='群聊固定回复群列表'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='group_fixed_reply_start',
            field=models.TimeField(blank=True, null=True, verbose_name='群聊固定回复开始时间'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='group_no_at_whitelist',
            field=models.JSONField(blank=True, default=list, help_text='当模式为at_and_whitelist时，这些群无需@也回复（群ID列表）', verbose_name='群聊无@回复白名单'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='group_reply_mode',
            field=models.CharField(choices=[('at_only', '仅@我时回复'), ('at_and_whitelist', '@我或白名单群回复'), ('all', '所有群消息都回复')], default='at_only', help_text='控制AI在群聊中何时回复', max_length=20, verbose_name='群聊AI回复模式'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='memory_rounds',
            field=models.IntegerField(default=10, help_text='读取最近N轮对话作为上下文（默认10）', verbose_name='AI记忆上下文轮数'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='non_text_reply_content',
            field=models.TextField(blank=True, default='', help_text='当策略为reply_text时填入固定回复文字；reply_template时填入话术模板名', verbose_name='非文本消息回复内容'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='non_text_reply_strategy',
            field=models.CharField(choices=[('ignore', '不回复'), ('reply_text', '回复指定文字'), ('reply_template', '回复话术模板')], default='reply_text', max_length=20, verbose_name='非文本/语音消息回复策略'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='reply_delay_max',
            field=models.IntegerField(default=3, help_text='AI回复前随机等待的最大秒数', verbose_name='回复延迟最大(秒)'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='reply_delay_min',
            field=models.IntegerField(default=1, help_text='AI回复前随机等待的最小秒数', verbose_name='回复延迟最小(秒)'),
        ),
        migrations.AddField(
            model_name='chatsetting',
            name='stop_reply_keywords',
            field=models.JSONField(blank=True, default=list, help_text='收到包含这些关键词的消息时，AI自动停止回复（转为人工）', verbose_name='AI停止回复关键词'),
        ),
    ]
