# Generated by Django 6.0.7 on 2026-08-03 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_follow', '0004_chat_setting_single_group_fields'),
        ('platform', '0018_expand_prompt_category'),
        ('wecom', '0010_messagefavorite_raw_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTagRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='规则备注')),
                ('keywords', models.JSONField(default=list, help_text='JSON 数组，例如 ["代理", "价格"]', verbose_name='关键词列表')),
                ('match_mode', models.CharField(choices=[('any', '任一关键词命中'), ('all', '全部关键词命中')], default='any', max_length=10, verbose_name='匹配模式')),
                ('scope', models.CharField(choices=[('personal', '仅个人消息'), ('group', '仅群消息'), ('both', '个人+群消息')], default='personal', max_length=10, verbose_name='应用范围')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('hit_count', models.IntegerField(default=0, verbose_name='历史命中次数')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最后命中时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_tag_rules', to='wecom.wecomdevice', verbose_name='所属企微账号')),
                ('target_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_tag_rules', to='wecom.wecomtag', verbose_name='命中的目标标签')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_tag_rules', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '自动贴标签规则',
                'verbose_name_plural': '自动贴标签规则',
                'db_table': 'mf_auto_tag_rule',
                'ordering': ['-created_at'],
            },
        ),
    ]
