# Generated by Django 6.0.7 on 2026-08-03 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_follow', '0005_autotagrule'),
        ('platform', '0018_expand_prompt_category'),
        ('wecom', '0011_alter_wecomtag_options_wecomcontact_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassSendTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('draft', '待执行'), ('enabled', '已开启'), ('disabled', '已关闭'), ('approved', '审核通过'), ('rejected', '审核拒绝')], default='draft', max_length=20, verbose_name='任务状态')),
                ('created_by', models.CharField(blank=True, default='', max_length=100, verbose_name='创建者')),
                ('started_by', models.CharField(blank=True, default='', max_length=100, verbose_name='开启人')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否开启')),
                ('daily_loop', models.BooleanField(default=False, verbose_name='每日循环执行')),
                ('planned_total', models.IntegerField(default=0, verbose_name='计划总人数')),
                ('planned_success', models.IntegerField(default=0, verbose_name='计划成功数')),
                ('planned_pending', models.IntegerField(default=0, verbose_name='计划待执行数')),
                ('planned_failed', models.IntegerField(default=0, verbose_name='计划失败数')),
                ('planned_network_error', models.IntegerField(default=0, verbose_name='计划网络异常数')),
                ('disabled_count', models.IntegerField(default=0, verbose_name='已禁用数')),
                ('reply_rate', models.FloatField(default=0.0, verbose_name='好友回复率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_send_tasks', to='wecom.wecomdevice', verbose_name='企微设备')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_send_tasks', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '精准群发任务',
                'verbose_name_plural': '精准群发任务',
                'db_table': 'mf_mass_send_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MassSendTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('contact', '好友'), ('group', '群聊'), ('all', '全部好友')], default='contact', max_length=20, verbose_name='目标类型')),
                ('tag_ids', models.JSONField(blank=True, default=list, verbose_name='标签筛选ID列表')),
                ('contact_ids', models.JSONField(blank=True, default=list, verbose_name='指定联系人ID列表')),
                ('group_ids', models.JSONField(blank=True, default=list, verbose_name='指定群聊ID列表')),
                ('filter_conditions', models.JSONField(blank=True, default=dict, help_text='如性别、地区、添加时间等', verbose_name='高级筛选条件')),
                ('estimated_count', models.IntegerField(default=0, verbose_name='预估发送人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='marketing_follow.masssendtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '发送对象',
                'verbose_name_plural': '发送对象',
                'db_table': 'mf_mass_send_target',
            },
        ),
        migrations.CreateModel(
            name='MassSendSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='定时执行时间')),
                ('daily_start_time', models.TimeField(blank=True, null=True, verbose_name='每日开始时间')),
                ('daily_end_time', models.TimeField(blank=True, null=True, verbose_name='每日结束时间')),
                ('daily_interval', models.IntegerField(default=0, help_text='0表示只执行一次', verbose_name='每日执行间隔(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='marketing_follow.masssendtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '执行时间',
                'verbose_name_plural': '执行时间',
                'db_table': 'mf_mass_send_schedule',
            },
        ),
        migrations.CreateModel(
            name='MassSendMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('msg_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('video', '视频'), ('audio', '语音'), ('file', '文件'), ('link', '链接'), ('miniprogram', '小程序'), ('channel', '视频号')], default='text', max_length=20, verbose_name='消息类型')),
                ('content', models.JSONField(blank=True, default=dict, help_text='按类型存储不同结构的数据', verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='marketing_follow.masssendtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '群发素材',
                'verbose_name_plural': '群发素材',
                'db_table': 'mf_mass_send_material',
                'ordering': ['order'],
            },
        ),
    ]
