# Generated by Django 6.0.7 on 2026-08-03 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_follow', '0006_mass_send_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentstask',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='momentstask',
            name='daily_loop',
            field=models.BooleanField(default=False, verbose_name='每日循环执行'),
        ),
        migrations.AddField(
            model_name='momentstask',
            name='failed',
            field=models.IntegerField(default=0, verbose_name='发送失败'),
        ),
        migrations.AddField(
            model_name='momentstask',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='是否开启'),
        ),
        migrations.AddField(
            model_name='momentstask',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='任务名称'),
        ),
        migrations.AddField(
            model_name='momentstask',
            name='network_error',
            field=models.IntegerField(default=0, verbose_name='网络异常'),
        ),
        migrations.AddField(
            model_name='momentstask',
            name='pending',
            field=models.IntegerField(default=0, verbose_name='待执行'),
        ),
        migrations.AddField(
            model_name='momentstask',
            name='started_by',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='开启人'),
        ),
        migrations.AddField(
            model_name='momentstask',
            name='success_sent',
            field=models.IntegerField(default=0, verbose_name='成功发送'),
        ),
        migrations.AddField(
            model_name='momentstask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='momentstask',
            name='wechat_total',
            field=models.IntegerField(default=0, verbose_name='微信总数'),
        ),
        migrations.AlterField(
            model_name='momentstask',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='朋友圈文案(旧)'),
        ),
        migrations.AlterField(
            model_name='momentstask',
            name='media_files',
            field=models.JSONField(blank=True, default=list, verbose_name='图片/视频文件列表(旧)'),
        ),
        migrations.AlterField(
            model_name='momentstask',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='定时发送时间(旧)'),
        ),
        migrations.AlterField(
            model_name='momentstask',
            name='status',
            field=models.CharField(choices=[('draft', '待执行'), ('enabled', '已开启'), ('disabled', '已关闭'), ('approved', '审核通过'), ('rejected', '审核拒绝')], default='draft', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='momentstask',
            name='visible_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='可见标签(旧)'),
        ),
        migrations.CreateModel(
            name='MomentsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('text', models.TextField(blank=True, default='', verbose_name='朋友圈文案')),
                ('random_emoji', models.BooleanField(default=False, verbose_name='随机表情')),
                ('media_type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('link', '链接')], default='image', max_length=20, verbose_name='媒体类型')),
                ('media_urls', models.JSONField(blank=True, default=list, verbose_name='媒体URL列表')),
                ('link_title', models.CharField(blank=True, default='', max_length=200, verbose_name='链接标题')),
                ('link_desc', models.CharField(blank=True, default='', max_length=500, verbose_name='链接描述')),
                ('link_url', models.URLField(blank=True, default='', max_length=500, verbose_name='链接URL')),
                ('link_pic_url', models.URLField(blank=True, default='', max_length=500, verbose_name='链接封面图')),
                ('ai_polish_enabled', models.BooleanField(default=False, verbose_name='执行发送前润色')),
                ('tone_template', models.CharField(blank=True, default='', max_length=100, verbose_name='调色要求模板')),
                ('prompt_template', models.CharField(blank=True, default='', max_length=100, verbose_name='提示词模板')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='marketing_follow.momentstask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '朋友圈内容',
                'verbose_name_plural': '朋友圈内容',
                'db_table': 'mf_moments_content',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MomentsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='定时执行时间')),
                ('daily_start_time', models.TimeField(blank=True, null=True, verbose_name='每日开始时间')),
                ('daily_end_time', models.TimeField(blank=True, null=True, verbose_name='每日结束时间')),
                ('daily_interval', models.IntegerField(default=0, help_text='0表示只执行一次', verbose_name='每日执行间隔(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='marketing_follow.momentstask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '朋友圈执行时间',
                'verbose_name_plural': '朋友圈执行时间',
                'db_table': 'mf_moments_schedule',
            },
        ),
        migrations.CreateModel(
            name='MomentsTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ids', models.JSONField(blank=True, default=list, verbose_name='微信账号ID列表')),
                ('estimated_count', models.IntegerField(default=0, verbose_name='预估微信数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='marketing_follow.momentstask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '朋友圈发送对象',
                'verbose_name_plural': '朋友圈发送对象',
                'db_table': 'mf_moments_target',
            },
        ),
    ]
