# Generated by Django 6.0.7 on 2026-07-24 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用记忆引擎')),
                ('short_term_window', models.IntegerField(default=20, verbose_name='短期记忆窗口（最近N条消息）')),
                ('summary_threshold', models.IntegerField(default=30, verbose_name='摘要触发阈值（消息数达到N条时生成摘要）')),
                ('retention_days', models.IntegerField(default=180, verbose_name='记忆保留天数')),
                ('max_summaries', models.IntegerField(default=100, verbose_name='最大摘要数量')),
                ('auto_summary', models.BooleanField(default=True, verbose_name='自动生成每日摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory_config', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '记忆配置',
                'verbose_name_plural': '记忆配置',
                'db_table': 'memory_config',
            },
        ),
        migrations.CreateModel(
            name='MemoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('preference', '用户偏好'), ('business', '业务事实'), ('entity', '实体信息'), ('decision', '历史决策'), ('general', '通用')], default='general', max_length=50, verbose_name='事实类别')),
                ('key', models.CharField(max_length=200, verbose_name='事实键')),
                ('value', models.TextField(verbose_name='事实值')),
                ('confidence', models.FloatField(default=0.8, verbose_name='置信度')),
                ('times_recalled', models.IntegerField(default=0, verbose_name='被召回次数')),
                ('last_recalled', models.DateTimeField(blank=True, null=True, verbose_name='最后召回时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.conversation', verbose_name='来源会话')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_facts', to='platform.tenant', verbose_name='所属租户')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_facts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '关键事实',
                'verbose_name_plural': '关键事实',
                'db_table': 'memory_fact',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryRecallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recalled_summaries', models.JSONField(blank=True, default=list, verbose_name='召回的摘要ID列表')),
                ('recalled_facts', models.JSONField(blank=True, default=list, verbose_name='召回的事实ID列表')),
                ('short_term_messages', models.IntegerField(default=0, verbose_name='短期记忆消息数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='记忆上下文Token数')),
                ('recall_strategy', models.CharField(choices=[('short_term', '仅短期记忆'), ('summary', '仅摘要召回'), ('fact', '仅事实召回'), ('hybrid', '混合召回')], default='hybrid', max_length=30, verbose_name='召回策略')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_logs', to='chat.conversation', verbose_name='关联会话')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recall_logs', to='chat.message', verbose_name='关联消息')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_recall_logs', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '记忆召回日志',
                'verbose_name_plural': '记忆召回日志',
                'db_table': 'memory_recall_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField(verbose_name='摘要日期')),
                ('title', models.CharField(max_length=300, verbose_name='摘要标题')),
                ('content', models.TextField(verbose_name='摘要内容')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='关键词条目')),
                ('key_facts', models.JSONField(blank=True, default=list, verbose_name='关键事实')),
                ('agent_codes', models.JSONField(blank=True, default=list, verbose_name='涉及智能体')),
                ('message_count', models.IntegerField(default=0, verbose_name='覆盖消息数')),
                ('token_count', models.IntegerField(default=0, verbose_name='估算Token数')),
                ('status', models.CharField(choices=[('active', '活跃'), ('archived', '已归档'), ('expired', '已过期')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='chat.conversation', verbose_name='关联会话')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_summaries', to='platform.tenant', verbose_name='所属租户')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_summaries', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '对话摘要',
                'verbose_name_plural': '对话摘要',
                'db_table': 'memory_summary',
                'ordering': ['-summary_date', '-created_at'],
            },
        ),
    ]
