# Generated by Django 6.0.7 on 2026-07-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型��称')),
                ('vendor', models.CharField(max_length=100, verbose_name='厂商')),
                ('type', models.CharField(choices=[('commercial', '商业模型'), ('open', '开源模型')], default='commercial', max_length=20, verbose_name='模型类型')),
                ('context_k', models.IntegerField(default=32, verbose_name='上下文长度(K)')),
                ('status', models.CharField(choices=[('ready', '就绪'), ('deploying', '部署中'), ('offline', '已下线')], default='ready', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('api_key', models.CharField(blank=True, default='', max_length=200, verbose_name='API Key（加密存储）')),
                ('endpoint', models.URLField(blank=True, default='', max_length=500, verbose_name='API 端点')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='扩展配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型',
                'db_table': 'model_gateway_model',
                'ordering': ['-created_at'],
            },
        ),
    ]
