# Generated by Django 6.0.7 on 2026-07-24 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_gateway', '0001_initial'),
        ('platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitBreakerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('closed', '关闭（正常）'), ('open', '打开（熔断中）'), ('half_open', '半开（试探中）')], default='closed', max_length=20, verbose_name='熔断器状态')),
                ('failure_count', models.IntegerField(default=0, verbose_name='连续失败次数')),
                ('failure_threshold', models.IntegerField(default=5, verbose_name='熔断阈值')),
                ('recovery_timeout', models.IntegerField(default=60, verbose_name='恢复超时(秒)')),
                ('last_failure', models.DateTimeField(blank=True, null=True, verbose_name='最后失败时间')),
                ('last_state_change', models.DateTimeField(blank=True, null=True, verbose_name='最后状态变更时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='circuit_state', to='model_gateway.aimodel', verbose_name='所属模型')),
            ],
            options={
                'verbose_name': '熔断器状态',
                'verbose_name_plural': '熔断器状态',
                'db_table': 'model_gateway_circuit',
            },
        ),
        migrations.CreateModel(
            name='ModelKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_alias', models.CharField(max_length=100, verbose_name='密钥别名')),
                ('api_key', models.CharField(max_length=500, verbose_name='API Key（加密存储）')),
                ('endpoint', models.URLField(blank=True, default='', max_length=500, verbose_name='API端点')),
                ('status', models.CharField(choices=[('active', '活跃'), ('disabled', '已禁用'), ('exhausted', '额度耗尽'), ('error', '异常')], default='active', max_length=20, verbose_name='状态')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级（数字越小优先级越高）')),
                ('daily_quota', models.IntegerField(default=0, verbose_name='每日配额（0=无限）')),
                ('daily_used', models.IntegerField(default=0, verbose_name='今日已用')),
                ('total_used', models.IntegerField(default=0, verbose_name='累计使用')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最后错误信息')),
                ('error_count', models.IntegerField(default=0, verbose_name='连续错误次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='model_gateway.aimodel', verbose_name='所属模型')),
            ],
            options={
                'verbose_name': '模型密钥',
                'verbose_name_plural': '模型密钥',
                'db_table': 'model_gateway_key',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='策略名称')),
                ('agent_code', models.CharField(max_length=50, verbose_name='智能体编码')),
                ('strategy_type', models.CharField(choices=[('priority', '优先级路由（主模型→备用模型）'), ('round_robin', '轮询负载均衡'), ('least_cost', '最低成本优先'), ('lowest_latency', '最低延迟优先'), ('weighted', '权重分配')], default='priority', max_length=30, verbose_name='路由策略类型')),
                ('weight_config', models.JSONField(blank=True, default=dict, verbose_name='权重配置')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('fallback_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_routes', to='model_gateway.aimodel', verbose_name='备用模型')),
                ('primary_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_routes', to='model_gateway.aimodel', verbose_name='主模型')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_strategies', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '路由策略',
                'verbose_name_plural': '路由策略',
                'db_table': 'model_gateway_routing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(blank=True, default='', max_length=50, verbose_name='智能体编码')),
                ('conversation_id', models.CharField(blank=True, default='', max_length=100, verbose_name='会话ID')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='输入Token数')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='输出Token数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token数')),
                ('cost', models.FloatField(default=0, verbose_name='费用估算（元）')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='响应耗时(ms)')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('timeout', '超时'), ('circuit_open', '熔断')], default='success', max_length=20, verbose_name='调用状态')),
                ('error_msg', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usages', to='model_gateway.aimodel', verbose_name='使用模型')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usages', to='platform.tenant', verbose_name='所属租户')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Token用量',
                'verbose_name_plural': 'Token用量',
                'db_table': 'model_gateway_token_usage',
                'ordering': ['-created_at'],
            },
        ),
    ]
