# Generated by Django 6.0.7 on 2026-07-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_gateway', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitbreakerstate',
            name='last_error',
            field=models.TextField(blank=True, default='', verbose_name='最后错误信息'),
        ),
    ]
