# Generated by Django 6.0.7 on 2026-07-24 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='技能名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='技能描述')),
                ('category', models.CharField(max_length=50, verbose_name='技能分类')),
                ('installed', models.BooleanField(default=False, verbose_name='是否已安装')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'db_table': 'tenant_skill',
            },
        ),
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(blank=True, default='', max_length=50, verbose_name='关联智能体')),
                ('agent_name', models.CharField(blank=True, default='', max_length=100, verbose_name='智能体名称')),
                ('amount', models.IntegerField(verbose_name='变动金额（正=消费，负=充值）')),
                ('reason', models.CharField(max_length=200, verbose_name='变动原因')),
                ('balance_after', models.IntegerField(verbose_name='变动后余额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger', to='platform.tenant', verbose_name='所属租户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分账本',
                'verbose_name_plural': '积分账本',
                'db_table': 'tenant_credit_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='连接器名称')),
                ('type', models.CharField(choices=[('erp', 'ERP'), ('b2b', 'B2B'), ('b2c', 'B2C'), ('third-party', '第三方')], max_length=20, verbose_name='连接器类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('icon_name', models.CharField(default='Boxes', max_length=50, verbose_name='图标名称')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('status', models.CharField(choices=[('connected', '已连接'), ('pending', '连接中'), ('disconnected', '未连接')], default='disconnected', max_length=20, verbose_name='连接状态')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='连接配置')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='上次同步')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_connectors', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '数据连接器',
                'verbose_name_plural': '数据连接器',
                'db_table': 'tenant_data_connector',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文档名称')),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'Word'), ('XLS', 'Excel'), ('MD', 'Markdown'), ('PPT', 'PPT')], max_length=10, verbose_name='文档类型')),
                ('size', models.CharField(max_length=20, verbose_name='文件大小')),
                ('folder', models.CharField(default='未分类', max_length=100, verbose_name='所属文件夹')),
                ('bound_agents', models.JSONField(blank=True, default=list, verbose_name='绑定智能体')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_docs', to='platform.tenant', verbose_name='所属租户')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '知识文档',
                'verbose_name_plural': '知识文档',
                'db_table': 'tenant_knowledge',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='素材名称')),
                ('type', models.CharField(default='image', max_length=20, verbose_name='素材类型')),
                ('size', models.CharField(max_length=20, verbose_name='文件大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='platform.tenant', verbose_name='所属租户')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '媒体素材',
                'verbose_name_plural': '媒体素材',
                'db_table': 'tenant_media',
            },
        ),
        migrations.CreateModel(
            name='SaaSConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='连接名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.CharField(choices=[('connected', '已连接'), ('pending', '连接中'), ('disconnected', '未连接')], default='pending', max_length=20, verbose_name='状态')),
                ('two_way', models.BooleanField(default=False, verbose_name='是否双向')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='上次同步')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_connections', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': 'SaaS连接',
                'verbose_name_plural': 'SaaS连接',
                'db_table': 'tenant_saas',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('agent_code', models.CharField(max_length=50, verbose_name='执行智能体')),
                ('schedule', models.CharField(max_length=100, verbose_name='调度规则')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='上次运行')),
                ('last_result', models.CharField(blank=True, default='', max_length=50, verbose_name='上次结果')),
                ('status', models.CharField(choices=[('success', '成功'), ('pending', '待执行'), ('failed', '失败')], default='pending', max_length=20, verbose_name='执行状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'db_table': 'tenant_task',
            },
        ),
    ]
