# Generated by Django 6.0.7 on 2026-07-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_ext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedoc',
            name='content_text',
            field=models.TextField(blank=True, default='', verbose_name='提取的文本内容（用于 RAG 检索）'),
        ),
    ]
