# Generated by Django 6.0.7 on 2026-07-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_ext', '0002_add_content_text_to_knowledge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ['-created_at'], 'verbose_name': '媒体素材', 'verbose_name_plural': '媒体素材'},
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='bound_agents',
            field=models.JSONField(blank=True, default=list, verbose_name='绑定智能体ID列表'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='素材描述'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media_assets/', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='file_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='文件URL'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='folder',
            field=models.CharField(default='全部', max_length=100, verbose_name='所属文件夹'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='外部链接'),
        ),
    ]
