# Generated by Django 6.0.7 on 2026-07-27 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0010_platformdatabase_platformenterprise'),
        ('tenant_ext', '0003_add_media_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnector',
            name='db_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='数据库连接配置'),
        ),
        migrations.AddField(
            model_name='dataconnector',
            name='db_type',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='数据库类型（mysql/api）'),
        ),
        migrations.AddField(
            model_name='dataconnector',
            name='enterprise_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='企业ID（统一社会信用代码）'),
        ),
        migrations.AddField(
            model_name='dataconnector',
            name='platform_enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_connectors', to='platform.platformenterprise', verbose_name='关联的平台企业'),
        ),
    ]
