# Generated by Django 6.0.7 on 2026-07-24 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='租户编码')),
                ('name', models.CharField(max_length=200, verbose_name='租户名称')),
                ('platform_name', models.CharField(blank=True, default='', max_length=200, verbose_name='平台名称')),
                ('status', models.CharField(choices=[('active', '已激活'), ('inactive', '已停用'), ('pending', '待审核')], default='active', max_length=20, verbose_name='状态')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenants', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '租户',
                'verbose_name_plural': '租户',
                'db_table': 'platform_tenant',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, verbose_name='角色编码')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('permissions', models.JSONField(default=list, verbose_name='权限清单')),
                ('can_manage_members', models.BooleanField(default=False, verbose_name='可管理成员')),
                ('can_assign_credits', models.BooleanField(default=False, verbose_name='可分配积分')),
                ('agents', models.JSONField(default=list, verbose_name='可用智能体列表')),
                ('views', models.JSONField(default=list, verbose_name='可见视图列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'platform_role',
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '套餐',
                'verbose_name_plural': '套餐',
                'db_table': 'platform_package',
            },
        ),
        migrations.CreateModel(
            name='DifyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configured', models.BooleanField(default=False, verbose_name='是否已配置')),
                ('connection_status', models.CharField(choices=[('connected', '已连接'), ('disconnected', '未连接'), ('error', '连接错误')], default='disconnected', max_length=20, verbose_name='连接状态')),
                ('last_test', models.DateTimeField(blank=True, null=True, verbose_name='最后测试时间')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dify_config', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': 'Dify配置',
                'verbose_name_plural': 'Dify配置',
                'db_table': 'platform_dify_config',
            },
        ),
        migrations.CreateModel(
            name='DifyWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='工作流编码')),
                ('agent_code', models.CharField(max_length=50, verbose_name='绑定智能体编码')),
                ('api_key', models.CharField(blank=True, default='', max_length=200, verbose_name='API Key')),
                ('base_url', models.CharField(blank=True, default='', max_length=300, verbose_name='Base URL')),
                ('dify_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='platform.difyconfig', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': 'Dify工作流',
                'verbose_name_plural': 'Dify工作流',
                'db_table': 'platform_dify_workflow',
                'unique_together': {('dify_config', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PackageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(max_length=50, verbose_name='智能体编码')),
                ('monthly', models.IntegerField(default=0, verbose_name='月度配额')),
                ('used', models.IntegerField(default=0, verbose_name='已使用')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='platform.package', verbose_name='所属套餐')),
            ],
            options={
                'verbose_name': '套餐配额',
                'verbose_name_plural': '套餐配额',
                'db_table': 'platform_package_quota',
                'unique_together': {('package', 'agent_code')},
            },
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50, verbose_name='智能体ID')),
                ('model_id', models.CharField(blank=True, default='', max_length=50, verbose_name='默认模型ID')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度')),
                ('max_retry', models.IntegerField(default=3, verbose_name='最大重试次数')),
                ('fallback_model_id', models.CharField(blank=True, default='', max_length=50, verbose_name='备用模型ID')),
                ('human_takeover_threshold', models.FloatField(default=0.6, verbose_name='人工接管阈值')),
                ('custom', models.JSONField(blank=True, default=dict, verbose_name='自定义配置')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '智能体配置',
                'verbose_name_plural': '智能体配置',
                'db_table': 'platform_agent_config',
                'unique_together': {('tenant', 'agent_id')},
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(default=0, verbose_name='积分余额')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线')], default='offline', max_length=20, verbose_name='在线状态')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='platform.role', verbose_name='角色')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='platform.tenant', verbose_name='所属租户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '租户成员',
                'verbose_name_plural': '租户成员',
                'db_table': 'platform_tenant_user',
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
