# Generated by Django 6.0.7 on 2026-07-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0002_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50, unique=True, verbose_name='智能体ID')),
                ('code', models.CharField(blank=True, default='', max_length=50, verbose_name='智能体编码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('role', models.CharField(blank=True, default='', max_length=200, verbose_name='角色描述')),
                ('emoji', models.CharField(blank=True, default='', max_length=10, verbose_name='Emoji')),
                ('scarf_color', models.CharField(blank=True, default='', max_length=50, verbose_name='围巾颜色')),
                ('accent', models.CharField(blank=True, default='', max_length=20, verbose_name='主题色（hex）')),
                ('description', models.TextField(blank=True, default='', verbose_name='详细描述')),
                ('capabilities', models.JSONField(blank=True, default=list, verbose_name='能力标签列表')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='统计数据')),
                ('default_workflow', models.JSONField(blank=True, default=list, verbose_name='默认工作流步骤')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '平台智能体',
                'verbose_name_plural': '平台智能体',
                'db_table': 'platform_agent',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='分类')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='步骤列表')),
                ('edges', models.JSONField(blank=True, default=list, verbose_name='连线列表')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工作流模板',
                'verbose_name_plural': '工作流模板',
                'db_table': 'platform_workflow_template',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='bound_data_bases',
            field=models.JSONField(blank=True, default=list, verbose_name='绑定的数据底座ID列表'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='bound_docs',
            field=models.JSONField(blank=True, default=list, verbose_name='绑定的知识文档ID列表'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='bound_images',
            field=models.JSONField(blank=True, default=list, verbose_name='绑定的营销素材ID列表'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='custom_description',
            field=models.TextField(blank=True, default='', verbose_name='自定义描述'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='custom_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='自定义名称'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='custom_role',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='自定义角色描述'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='custom_scarf_color',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='自定义围巾颜色'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='custom_workflow',
            field=models.JSONField(blank=True, default=list, verbose_name='自定义工作流步骤'),
        ),
    ]
