# Generated by Django 6.0.7 on 2026-07-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0004_platformrole_platformuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='手机号'),
        ),
    ]
