# Generated by Django 6.0.7 on 2026-07-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0005_add_phone_to_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='enterprise_id',
            field=models.CharField(blank=True, default='', help_text='用于识别租户第一层的数据底座', max_length=50, verbose_name='企业ID（统一社会信用代码）'),
        ),
    ]
