# Generated by Django 6.0.7 on 2026-07-27 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0006_add_enterprise_id_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='default_workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='platform.workflowtemplate', verbose_name='默认工作流模板'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='custom_workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_configs', to='platform.workflowtemplate', verbose_name='自定义工作流模板'),
        ),
    ]
