# Generated by Django 6.0.7 on 2026-07-27 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0007_agent_workflow_template_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='角色编码')),
                ('category', models.CharField(blank=True, choices=[('purchase', '采购'), ('sales', '销售'), ('ops', '运营'), ('flow', '流向'), ('academic', '学术'), ('control', '中控'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, default='', verbose_name='角色定位 / 专业能力')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '智能体角色',
                'verbose_name_plural': '智能体角色',
                'db_table': 'platform_agent_role',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_agent', to='platform.agentrole', verbose_name='绑定的智能体角色'),
        ),
    ]
