# Generated by Django 6.0.7 on 2026-07-27 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0009_tenant_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='平台编码')),
                ('name', models.CharField(max_length=200, verbose_name='平台名称')),
                ('type', models.CharField(choices=[('erp', 'ERP'), ('b2b', 'B2B'), ('b2c', 'B2C'), ('third_party', '第三方')], max_length=20, verbose_name='平台类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('icon_name', models.CharField(default='Database', max_length=50, verbose_name='图标名称')),
                ('api_base_url', models.CharField(blank=True, default='', max_length=500, verbose_name='同步API地址')),
                ('api_token', models.CharField(blank=True, default='', max_length=500, verbose_name='API Token（Bearer）')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='是否启用同步')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('last_sync_status', models.CharField(blank=True, default='', max_length=20, verbose_name='最后同步状态')),
                ('last_sync_error', models.TextField(blank=True, default='', verbose_name='最后同步错误')),
                ('total_enterprises', models.IntegerField(default=0, verbose_name='同步企业总数')),
                ('linked_tenant_count', models.IntegerField(default=0, verbose_name='已匹配租户数')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '平台数据库',
                'verbose_name_plural': '平台数据库',
                'db_table': 'platform_database',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformEnterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_id', models.CharField(max_length=100, verbose_name='企业ID（统一社会信用代码）')),
                ('enterprise_name', models.CharField(blank=True, default='', max_length=200, verbose_name='企业名称')),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL 直连'), ('api', 'HTTP API')], default='mysql', max_length=10, verbose_name='数据库类型')),
                ('db_config', models.JSONField(blank=True, default=dict, verbose_name='数据库连接配置')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='最后同步时间')),
                ('matched_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_enterprises', to='platform.tenant', verbose_name='匹配的租户')),
                ('platform_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprises', to='platform.platformdatabase', verbose_name='所属平台')),
            ],
            options={
                'verbose_name': '平台企业',
                'verbose_name_plural': '平台企业',
                'db_table': 'platform_enterprise',
                'unique_together': {('platform_database', 'enterprise_id')},
            },
        ),
    ]
