# Generated by Django 6.0.7 on 2026-07-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0010_platformdatabase_platformenterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='capability_mode',
            field=models.CharField(choices=[('builtin', '天网大脑AI能力'), ('external', '外部平台AI能力')], default='builtin', max_length=20, verbose_name='AI能力模式'),
        ),
        migrations.AddField(
            model_name='agent',
            name='external_workflow_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='外部平台工作流编码'),
        ),
    ]
