# Generated by Django 6.0.7 on 2026-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0011_agent_capability_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='avatar',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='自定义头像URL'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='custom_avatar',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='自定义头像URL'),
        ),
    ]
