# Generated by Django 6.0.7 on 2026-07-28 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0013_tenantuser_credit_allocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCreditRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(max_length=50, unique=True, verbose_name='智能体编码')),
                ('agent_name', models.CharField(blank=True, default='', max_length=100, verbose_name='智能体名称')),
                ('coefficient', models.FloatField(default=1.0, verbose_name='消耗系数（1.0=标准）')),
                ('free_deduction', models.BooleanField(default=False, verbose_name='是否免扣积分')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '智能体积分规则',
                'verbose_name_plural': '智能体积分规则',
                'db_table': 'platform_agent_credit_rule',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CreditConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_per_credit', models.FloatField(default=1000, verbose_name='1积分兑换Token数')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.1, max_digits=10, verbose_name='积分单价（元/积分）')),
                ('free_credits_on_register', models.IntegerField(default=1000, verbose_name='注册赠送积分')),
                ('min_purchase_credits', models.IntegerField(default=100, verbose_name='最小购买积分')),
                ('enable_online_pay', models.BooleanField(default=False, verbose_name='是否启用在线支付')),
                ('enable_offline_pay', models.BooleanField(default=True, verbose_name='是否启用公对公转账')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '积分配置',
                'verbose_name_plural': '积分配置',
                'db_table': 'platform_credit_config',
            },
        ),
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('credits', models.IntegerField(verbose_name='积分数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格（元）')),
                ('bonus_credits', models.IntegerField(default=0, verbose_name='赠送积分')),
                ('is_popular', models.BooleanField(default=False, verbose_name='是否热门')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '积分套餐',
                'verbose_name_plural': '积分套餐',
                'db_table': 'platform_credit_package',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CreditOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('credits', models.IntegerField(verbose_name='购买积分')),
                ('bonus_credits', models.IntegerField(default=0, verbose_name='赠送积分')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额（元）')),
                ('payment_method', models.CharField(choices=[('offline', '公对公转账'), ('online', '在线支付'), ('manual', '管理员充值')], default='offline', max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('confirmed', '已确认到账'), ('cancelled', '已取消'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('proof_file', models.CharField(blank=True, default='', max_length=500, verbose_name='付款凭证URL')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_credit_orders', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_orders', to='platform.tenant', verbose_name='租户')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform.creditpackage', verbose_name='套餐')),
            ],
            options={
                'verbose_name': '积分订单',
                'verbose_name_plural': '积分订单',
                'db_table': 'platform_credit_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
