# Generated by Django 6.0.7 on 2026-07-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0014_credit_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='详细地址'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='所在城市'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='province',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='所在省份'),
        ),
    ]
