# Generated by Django 6.0.7 on 2026-07-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0015_tenant_address_tenant_city_tenant_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='channel',
            field=models.CharField(blank=True, choices=[('clinic', '诊所'), ('pharmacy', '药店'), ('hospital', '医院')], default='', help_text='租户客户类型，用于产品可销渠道匹配', max_length=20, verbose_name='客户渠道'),
        ),
    ]
