# Generated by Django 6.0.7 on 2026-07-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0016_tenant_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.CharField(blank=True, choices=[('recommend', '推荐'), ('platform', '平台运营'), ('marketing', '营销跟客'), ('flow', '流向管控'), ('purchase', '智能采购'), ('academic', '学术培训'), ('quick', '快采'), ('collective', '集采'), ('search', '找品')], default='recommend', max_length=20, verbose_name='分类（首页提示词/采购对话快捷输入使用）'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_type',
            field=models.CharField(choices=[('home', '首页提示词'), ('chat', '普通提示词'), ('purchase_chat', '采购对话提示词')], max_length=20, verbose_name='类型'),
        ),
    ]
