# Generated by Django 6.0.7 on 2026-07-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0017_prompt_purchase_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.CharField(blank=True, default='recommend', max_length=50, verbose_name='分类（首页提示词/采购对话快捷输入使用，支持自定义自由输入）'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_type',
            field=models.CharField(choices=[('home', '首页提示词'), ('chat', '普通提示词'), ('purchase_chat', '采购对话提示词'), ('purchase_home', '采购兔首页提示词')], max_length=20, verbose_name='类型'),
        ),
    ]
