# Generated by Django 6.0.7 on 2026-07-28 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0015_tenant_address_tenant_city_tenant_province'),
        ('public_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicproduct',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='库存数量'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='所在城市'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='province',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='所在省份'),
        ),
        migrations.CreateModel(
            name='CollectivePurchaseAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='公告描述')),
                ('announce_time', models.DateTimeField(verbose_name='公告时间')),
                ('quote_deadline', models.DateTimeField(verbose_name='报价截止时间')),
                ('order_deadline', models.DateTimeField(verbose_name='下单截止时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('announced', '已公告'), ('collecting', '收集中'), ('quoting', '供应商报价中'), ('distributed', '报价已分发'), ('ordering', '下单中'), ('closed', '已关闭'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('product_keywords', models.TextField(blank=True, default='', verbose_name='产品关键词（逗号分隔，空=全部）')),
                ('supplier_ids', models.TextField(blank=True, default='', verbose_name='指定供应商ID（逗号分隔，空=全部）')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to='platform.platformuser', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '集采公告',
                'verbose_name_plural': '集采公告',
                'db_table': 'pdb_collective_announcement',
                'ordering': ['-announce_time'],
            },
        ),
        migrations.CreateModel(
            name='SupplierAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='登录用户名')),
                ('password_hash', models.CharField(max_length=200, verbose_name='密码哈希')),
                ('api_token', models.CharField(blank=True, default='', max_length=200, verbose_name='API Token')),
                ('contact_name', models.CharField(blank=True, default='', max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='联系电话')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='public_database.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '供应商账号',
                'verbose_name_plural': '供应商账号',
                'db_table': 'pdb_supplier_account',
            },
        ),
        migrations.CreateModel(
            name='CollectiveParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='需求数量')),
                ('quoted_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='报价单价')),
                ('quoted_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='报价总价')),
                ('final_quantity', models.IntegerField(blank=True, null=True, verbose_name='最终确认数量')),
                ('status', models.CharField(choices=[('registered', '已登记'), ('quoted', '已收到报价'), ('ordered', '已下单'), ('declined', '已放弃')], default='registered', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collective_participations', to='public_database.publicproduct', verbose_name='产品')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collective_participations', to='public_database.supplier', verbose_name='供应商')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collective_participations', to='platform.tenant', verbose_name='租户')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='public_database.collectivepurchaseannouncement', verbose_name='集采公告')),
            ],
            options={
                'verbose_name': '集采参与',
                'verbose_name_plural': '集采参与',
                'db_table': 'pdb_collective_participation',
                'ordering': ['-created_at'],
                'unique_together': {('announcement', 'tenant', 'product', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='SupplierDeliveryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, default='', max_length=50, verbose_name='省份（空=全国）')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='城市（空=全省）')),
                ('delivery_hours', models.IntegerField(default=48, verbose_name='配送时长（小时）')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='起订金额')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_rules', to='public_database.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '供应商配送规则',
                'verbose_name_plural': '供应商配送规则',
                'db_table': 'pdb_supplier_delivery_rule',
                'ordering': ['supplier', 'province', 'city'],
                'unique_together': {('supplier', 'province', 'city')},
            },
        ),
    ]
