# Generated by Django 6.0.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0015_tenant_address_tenant_city_tenant_province'),
        ('public_database', '0002_publicproduct_stock_quantity_supplier_city_and_more'),
    ]

    operations = [
        # PublicProduct 新增 image_url
        migrations.AddField(
            model_name='publicproduct',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='产品图片URL'),
        ),
        # ProcurementOrder 新增 tracking_number
        migrations.AddField(
            model_name='procurementorder',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='物流单号'),
        ),
        # 新增 OrderReturn 模型
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=50, unique=True, verbose_name='退货编号')),
                ('reason', models.TextField(verbose_name='退货原因')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='退款金额')),
                ('status', models.CharField(choices=[('requested', '待审核'), ('approved', '已同意'), ('rejected', '已拒绝'), ('returning', '退货中'), ('completed', '已完成'), ('cancelled', '已取消')], default='requested', max_length=20, verbose_name='状态')),
                ('supplier_remark', models.TextField(blank=True, default='', verbose_name='供应商处理备注')),
                ('return_tracking_number', models.CharField(blank=True, default='', max_length=200, verbose_name='退货物流单号')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='public_database.procurementorder', verbose_name='关联订单')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='public_database.supplier', verbose_name='供应商')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_returns', to='platform.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '退货申请',
                'verbose_name_plural': '退货申请',
                'db_table': 'pdb_order_return',
                'ordering': ['-created_at'],
            },
        ),
    ]
