# Generated by Django 6.0.7 on 2026-07-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_database', '0006_supplier_wallet_withdrawal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='suppliernotification',
            new_name='pdb_supplie_supplie_b98fe4_idx',
            old_name='pdb_sn_supplier_read_idx',
        ),
        migrations.RenameIndex(
            model_name='suppliernotification',
            new_name='pdb_supplie_supplie_9cd68f_idx',
            old_name='pdb_sn_supplier_created_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrecord',
            new_name='pdb_withdra_supplie_ea8222_idx',
            old_name='pdb_withdr_suppli_status_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrecord',
            new_name='pdb_withdra_created_78a50f_idx',
            old_name='pdb_withdr_created_idx',
        ),
    ]
