# Generated by Django 6.0.7 on 2026-07-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_database', '0007_rename_pdb_sn_supplier_read_idx_pdb_supplie_supplie_b98fe4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicproduct',
            name='sales_channels',
            field=models.JSONField(default=list, help_text='可销渠道类型，如["诊所","药店","医院"]，空列表=全渠道', verbose_name='可销渠道'),
        ),
        migrations.AddField(
            model_name='publicproduct',
            name='sales_regions',
            field=models.JSONField(default=list, help_text='可销省/市列表，如 [{"province":"广东","cities":["广州","深圳"]}]，空列表=全国', verbose_name='可销区域'),
        ),
    ]
