# Generated by Django 6.0.7 on 2026-07-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_database', '0008_publicproduct_sales_channels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierwallet',
            name='bank_verify_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='银行卡修改验证码'),
        ),
        migrations.AddField(
            model_name='supplierwallet',
            name='bank_verify_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='验证码过期时间'),
        ),
    ]
