# Generated by Django 6.0.7 on 2026-07-29 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0016_tenant_channel'),
        ('public_database', '0010_alter_supplierdeliveryrule_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierqualification',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='文件大小(字节)'),
        ),
        migrations.AddField(
            model_name='supplierqualification',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='发证日期'),
        ),
        migrations.AddField(
            model_name='supplierqualification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='supplierdeliveryrule',
            name='city',
            field=models.JSONField(default=list, help_text='配送城市列表，如["广州","深圳"]；空列表表示该省全部城市', verbose_name='城市列表（空=全省）'),
        ),
        migrations.AlterField(
            model_name='supplierqualification',
            name='qualification_type',
            field=models.CharField(choices=[('business_license', '营业执照'), ('gsp_certificate', 'GSP认证证书'), ('drug_license', '药品经营许可证'), ('medical_device_license', '医疗器械经营许可证'), ('food_license', '食品经营许可证'), ('pharmaceutical_production_license', '药品生产许可证'), ('import_drug_license', '进口药品注册证'), ('other', '其他')], max_length=50, verbose_name='资质类型'),
        ),
        migrations.CreateModel(
            name='FirstOperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(max_length=50, unique=True, verbose_name='首营编号')),
                ('buyer_qualifications', models.JSONField(blank=True, default=list, verbose_name='买方资质快照')),
                ('seller_qualifications', models.JSONField(blank=True, default=list, verbose_name='卖方资质快照')),
                ('buyer_confirmed', models.BooleanField(default=False, verbose_name='买方已确认')),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='买方确认时间')),
                ('seller_confirmed', models.BooleanField(default=False, verbose_name='卖方已确认')),
                ('seller_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='卖方确认时间')),
                ('buyer_remark', models.TextField(blank=True, default='', verbose_name='买方备注')),
                ('seller_remark', models.TextField(blank=True, default='', verbose_name='卖方备注')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('exchanged', '资质已互换'), ('signing', '签章中'), ('signed', '已签章'), ('rejected', '已拒绝'), ('expired', '已过期')], default='draft', max_length=20, verbose_name='状态')),
                ('e_signature_service', models.CharField(blank=True, default='', max_length=50, verbose_name='签章服务商')),
                ('e_signature_contract_id', models.CharField(blank=True, default='', max_length=200, verbose_name='签章合同ID')),
                ('e_signature_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='签章时间')),
                ('e_signature_contract_url', models.URLField(blank=True, default='', max_length=500, verbose_name='签章合同下载URL')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('created_by', models.CharField(blank=True, default='', max_length=100, verbose_name='发起人')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('buyer_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_operations_as_buyer', to='platform.tenant', verbose_name='买方租户')),
                ('seller_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_operations_as_seller', to='public_database.supplier', verbose_name='卖方供应商')),
            ],
            options={
                'verbose_name': '首营记录',
                'verbose_name_plural': '首营记录',
                'db_table': 'pdb_first_operation_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='qualificationexchange',
            name='first_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_exchanges', to='public_database.firstoperationrecord', verbose_name='关联首营记录'),
        ),
        migrations.CreateModel(
            name='TenantQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(choices=[('business_license', '营业执照'), ('gsp_certificate', 'GSP认证证书'), ('drug_license', '药品经营许可证'), ('medical_device_license', '医疗器械经营许可证'), ('food_license', '食品经营许可证'), ('pharmaceutical_production_license', '药品生产许可证'), ('import_drug_license', '进口药品注册证'), ('other', '其他')], max_length=50, verbose_name='资质类型')),
                ('qualification_name', models.CharField(max_length=200, verbose_name='资质名称')),
                ('file_url', models.URLField(blank=True, default='', max_length=500, verbose_name='文件URL')),
                ('file_name', models.CharField(blank=True, default='', max_length=200, verbose_name='文件名')),
                ('license_number', models.CharField(blank=True, default='', max_length=100, verbose_name='证书编号')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='发证日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('status', models.CharField(choices=[('valid', '有效'), ('expiring', '即将到期'), ('expired', '已过期')], default='valid', max_length=20, verbose_name='状态')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='platform.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '租户资质',
                'verbose_name_plural': '租户资质',
                'db_table': 'pdb_tenant_qualification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='firstoperationrecord',
            index=models.Index(fields=['buyer_tenant', 'status'], name='pdb_first_o_buyer_t_b41069_idx'),
        ),
        migrations.AddIndex(
            model_name='firstoperationrecord',
            index=models.Index(fields=['seller_supplier', 'status'], name='pdb_first_o_seller__1e92a0_idx'),
        ),
        migrations.AddIndex(
            model_name='firstoperationrecord',
            index=models.Index(fields=['valid_until'], name='pdb_first_o_valid_u_68bd6f_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantqualification',
            index=models.Index(fields=['tenant', 'status'], name='pdb_tenant__tenant__a62b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantqualification',
            index=models.Index(fields=['expiry_date'], name='pdb_tenant__expiry__7f43b3_idx'),
        ),
    ]
