# Generated by Django 6.0.7 on 2026-08-01 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0018_expand_prompt_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WecomDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100, unique=True, verbose_name='设备GUID')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('qw_user_id', models.CharField(blank=True, default='', max_length=100, verbose_name='企微用户ID')),
                ('qw_account', models.CharField(blank=True, default='', max_length=100, verbose_name='企微账号(手机号)')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('banned', '已封禁')], default='offline', max_length=20, verbose_name='设备状态')),
                ('ai_enabled', models.BooleanField(default=True, verbose_name='设备级AI开关')),
                ('callback_url', models.URLField(blank=True, default='', verbose_name='回调地址')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('qiwe_token', models.CharField(blank=True, default='', max_length=500, verbose_name='QiWe Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wecom_devices', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '企微设备',
                'verbose_name_plural': '企微设备',
                'db_table': 'wecom_device',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WecomContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_userid', models.CharField(max_length=200, unique=True, verbose_name='企微外部联系人ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='企微昵称')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='企微备注名')),
                ('avatar', models.URLField(blank=True, default='', verbose_name='头像URL')),
                ('enterprise_id', models.CharField(blank=True, default='', max_length=100, verbose_name='统一社会信用代码')),
                ('ai_hosted', models.BooleanField(default=True, verbose_name='客户级AI托管开关')),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='最后联系时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wecom_contacts', to='platform.tenant', verbose_name='所属租户')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='wecom.wecomdevice', verbose_name='所属企微账号')),
            ],
            options={
                'verbose_name': '企微联系人',
                'verbose_name_plural': '企微联系人',
                'db_table': 'wecom_contact',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WecomGroupRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=200, unique=True, verbose_name='群ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='群名')),
                ('owner_id', models.CharField(blank=True, default='', max_length=200, verbose_name='群主ID')),
                ('member_count', models.IntegerField(default=0, verbose_name='成员数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_rooms', to='wecom.wecomdevice', verbose_name='所属设备')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wecom_group_rooms', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '企微群聊',
                'verbose_name_plural': '企微群聊',
                'db_table': 'wecom_group_room',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WecomMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('file', '文件'), ('voice', '语音')], default='image', max_length=20, verbose_name='文件类型')),
                ('qiwe_file_id', models.CharField(blank=True, default='', max_length=500, verbose_name='QiWe文件ID')),
                ('local_path', models.CharField(blank=True, default='', max_length=500, verbose_name='本地存储路径')),
                ('url', models.URLField(blank=True, default='', verbose_name='可访问URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wecom_media_files', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '企微媒体文件',
                'verbose_name_plural': '企微媒体文件',
                'db_table': 'wecom_media_file',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WecomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', '收到'), ('outbound', '发出')], max_length=20, verbose_name='消息方向')),
                ('msg_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('link', '链接'), ('video', '视频'), ('voice', '语音')], default='text', max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(blank=True, default='', verbose_name='消息内容')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='QiWe原始回调数据')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='是否AI生成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='消息时间')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wecom.wecomcontact', verbose_name='关联联系人')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wecom.wecomdevice', verbose_name='所属设备')),
                ('media_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='wecom.wecommediafile', verbose_name='媒体附件')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wecom_messages', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '企微消息',
                'verbose_name_plural': '企微消息',
                'db_table': 'wecom_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WecomTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(blank=True, default='', max_length=100, verbose_name='QiWe标签ID')),
                ('name', models.CharField(max_length=100, verbose_name='标签名称')),
                ('color', models.CharField(blank=True, default='#1890ff', max_length=20, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wecom_tags', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '企微标签',
                'verbose_name_plural': '企微标签',
                'db_table': 'wecom_tag',
                'ordering': ['id'],
            },
        ),
    ]
