# Generated by Django 6.0.7 on 2026-08-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0018_expand_prompt_category'),
        ('wecom', '0003_device_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(choices=[('text', '文本'), ('emoji', '表情'), ('image', '图片'), ('file', '文件'), ('voice', '语音')], default='text', max_length=20, verbose_name='收藏类型')),
                ('content', models.TextField(blank=True, default='', verbose_name='文本内容/显示文字')),
                ('media_file_url', models.URLField(blank=True, default='', verbose_name='媒体文件URL')),
                ('media_file_name', models.CharField(blank=True, default='', max_length=500, verbose_name='媒体文件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_favorites', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '消息收藏',
                'verbose_name_plural': '消息收藏',
                'db_table': 'wecom_message_favorite',
                'ordering': ['-created_at'],
            },
        ),
    ]
