# Generated by Django 6.0.7 on 2026-08-02 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecom', '0004_message_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='wecommessage',
            name='is_recalled',
            field=models.BooleanField(default=False, verbose_name='是否已撤回'),
        ),
        migrations.AddField(
            model_name='wecommessage',
            name='quoted_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='wecom.wecommessage', verbose_name='引用的消息'),
        ),
    ]
