# Generated by Django 6.0.7 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecom', '0005_add_recall_and_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='wecommessage',
            name='msg_server_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='QiWe消息服务器ID'),
        ),
        migrations.AddField(
            model_name='wecommessage',
            name='msg_unique_identifier',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='QiWe消息唯一标识'),
        ),
    ]
