# Generated by Django 6.0.7 on 2026-08-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecom', '0006_add_msg_server_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wecommessage',
            name='msg_type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('link', '链接'), ('video', '视频'), ('voice', '语音'), ('miniprogram', '小程序')], default='text', max_length=20, verbose_name='消息类型'),
        ),
    ]
