# Generated by Django 6.0.7 on 2026-08-02 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecom', '0007_alter_wecommessage_msg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wecommessage',
            name='conversation_type',
            field=models.CharField(choices=[('personal', '个人'), ('group', '群聊')], default='personal', max_length=20, verbose_name='会话类型'),
        ),
        migrations.AddField(
            model_name='wecommessage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='wecom.wecomgrouproom', verbose_name='所属群聊'),
        ),
    ]
