# Generated by Django 6.0.7 on 2026-08-02 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecom', '0008_add_group_chat_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wecommessage',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wecom.wecomcontact', verbose_name='关联联系人'),
        ),
    ]
