# Generated by Django 6.0.7 on 2026-08-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecom', '0009_contact_nullable_for_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefavorite',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='原始消息数据（小程序等需要）'),
        ),
        migrations.AlterField(
            model_name='messagefavorite',
            name='msg_type',
            field=models.CharField(choices=[('text', '文本'), ('emoji', '表情'), ('image', '图片'), ('file', '文件'), ('voice', '语音'), ('miniprogram', '小程序')], default='text', max_length=20, verbose_name='收藏类型'),
        ),
    ]
