# Generated by Django 6.0.7 on 2026-08-03 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0018_expand_prompt_category'),
        ('wecom', '0010_messagefavorite_raw_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wecomtag',
            options={'ordering': ['order', 'id'], 'verbose_name': '企微标签', 'verbose_name_plural': '企微标签'},
        ),
        migrations.AddField(
            model_name='wecomcontact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='wecom.wecomtag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='wecomgrouproom',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='group_rooms', to='wecom.wecomtag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='wecomtag',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='wecom.wecomdevice', verbose_name='所属企微账号'),
        ),
        migrations.AddField(
            model_name='wecomtag',
            name='is_customer_level',
            field=models.BooleanField(default=False, verbose_name='是否客户等级'),
        ),
        migrations.AddField(
            model_name='wecomtag',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.CreateModel(
            name='WecomTagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(blank=True, default='', max_length=100, verbose_name='QiWe分组ID')),
                ('name', models.CharField(max_length=100, verbose_name='分组名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_customer_level', models.BooleanField(default=False, verbose_name='是否客户等级分组')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_groups', to='wecom.wecomdevice', verbose_name='所属企微账号')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wecom_tag_groups', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '企微标签分组',
                'verbose_name_plural': '企微标签分组',
                'db_table': 'wecom_tag_group',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='wecomtag',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='wecom.wecomtaggroup', verbose_name='所属分组'),
        ),
    ]
