# Generated by Django 6.0.7 on 2026-08-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecom', '0013_wecom_global_config_wecom_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wecomdevice',
            name='qiwe_token',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='QiWe Token（旧字段，保留兼容）'),
        ),
        migrations.AlterField(
            model_name='wecomglobalconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wecomnumber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
