# Generated by Django 6.0.7 on 2026-08-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecom', '0015_contact_unique_together_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='wecomgrouproom',
            name='member_user_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='群成员userId列表'),
        ),
        migrations.AlterField(
            model_name='wecomgrouproom',
            name='group_id',
            field=models.CharField(max_length=200, verbose_name='群ID'),
        ),
        migrations.AlterUniqueTogether(
            name='wecomgrouproom',
            unique_together={('group_id', 'device')},
        ),
    ]
