# Generated by Django 6.0.7 on 2026-07-24 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('ip_whitelist', 'IP白名单'), ('ip_blacklist', 'IP黑名单'), ('time_restriction', '时间限制'), ('api_restriction', 'API限制'), ('data_restriction', '数据限制')], max_length=30, verbose_name='规则类型')),
                ('pattern', models.CharField(max_length=500, verbose_name='匹配模式')),
                ('action', models.CharField(choices=[('allow', '允许'), ('deny', '拒绝'), ('warn', '警告')], default='allow', max_length=20, verbose_name='动作')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '访问控制规则',
                'verbose_name_plural': '访问控制规则',
                'db_table': 'security_access_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('query', '查询'), ('export', '导出'), ('upload', '上传'), ('download', '下载'), ('config_change', '配置变更'), ('permission_change', '权限变更'), ('data_access', '数据访问'), ('api_call', 'API调用'), ('security_event', '安全事件')], max_length=50, verbose_name='操作类型')),
                ('resource_type', models.CharField(blank=True, default='', max_length=100, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, default='', max_length=100, verbose_name='资源ID')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('method', models.CharField(blank=True, default='', max_length=10, verbose_name='HTTP方法')),
                ('path', models.CharField(blank=True, default='', max_length=500, verbose_name='请求路径')),
                ('ip_address', models.CharField(blank=True, default='', max_length=50, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User-Agent')),
                ('request_body', models.JSONField(blank=True, default=dict, verbose_name='请求参数（脱敏后）')),
                ('response_status', models.IntegerField(default=200, verbose_name='响应状态码')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('risk_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='low', max_length=20, verbose_name='风险等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='platform.tenant', verbose_name='所属租户')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'security_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_enabled', models.BooleanField(default=True, verbose_name='操作审计')),
                ('data_isolation', models.BooleanField(default=True, verbose_name='数据隔离')),
                ('mask_phone', models.BooleanField(default=True, verbose_name='手机号脱敏')),
                ('mask_id_card', models.BooleanField(default=True, verbose_name='身份证脱敏')),
                ('mask_bank_card', models.BooleanField(default=True, verbose_name='银行卡脱敏')),
                ('mask_email', models.BooleanField(default=False, verbose_name='邮箱脱敏')),
                ('mask_name', models.BooleanField(default=False, verbose_name='姓名脱敏')),
                ('request_sign_enabled', models.BooleanField(default=False, verbose_name='请求签名验证')),
                ('sign_secret', models.CharField(blank=True, default='', max_length=200, verbose_name='签名密钥')),
                ('rate_limit_enabled', models.BooleanField(default=True, verbose_name='API限流')),
                ('rate_limit_per_minute', models.IntegerField(default=60, verbose_name='每分钟请求上限')),
                ('sensitive_keywords', models.JSONField(blank=True, default=list, verbose_name='敏感词列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_config', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '安全配置',
                'verbose_name_plural': '安全配置',
                'db_table': 'security_config',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('brute_force', '暴力破解'), ('rate_limit_exceeded', '限流触发'), ('unauthorized_access', '越权访问'), ('sensitive_data', '敏感数据访问'), ('abnormal_export', '异常导出'), ('injection_attempt', '注入攻击'), ('signature_invalid', '签名验证失败')], max_length=50, verbose_name='事件类型')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=20, verbose_name='严重程度')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('ip_address', models.CharField(blank=True, default='', max_length=50, verbose_name='IP地址')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolve_note', models.TextField(blank=True, default='', verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_events', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='platform.tenant', verbose_name='所属租户')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '安全事件',
                'verbose_name_plural': '安全事件',
                'db_table': 'security_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
