# Generated by Django 6.0.7 on 2026-07-24 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('type', models.CharField(choices=[('连锁药店', '连锁药店'), ('单体药店', '单体药店'), ('诊所', '诊所'), ('医院', '医院')], max_length=20, verbose_name='客户类型')),
                ('contact', models.CharField(max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('monthly_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='月采购额')),
                ('last_order', models.DateTimeField(blank=True, null=True, verbose_name='最后下单时间')),
                ('level', models.CharField(choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级')], default='B', max_length=10, verbose_name='客户等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'tenant_customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='订单金额')),
                ('items_count', models.IntegerField(default=1, verbose_name='商品数量')),
                ('status', models.CharField(choices=[('已完成', '已完成'), ('配送中', '配送中'), ('待发货', '待发货'), ('已取消', '已取消')], default='待发货', max_length=20, verbose_name='状态')),
                ('time', models.DateTimeField(verbose_name='下单时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tenant_db.customer', verbose_name='客户')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'tenant_order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('spec', models.CharField(blank=True, default='', max_length=100, verbose_name='规格')),
                ('unit', models.CharField(default='盒', max_length=20, verbose_name='单位')),
                ('category', models.CharField(max_length=100, verbose_name='品类')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('status', models.CharField(choices=[('正常', '正常'), ('库存预警', '库存预警'), ('已下架', '已下架')], default='正常', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'tenant_product',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='仓库名称')),
                ('location', models.CharField(max_length=200, verbose_name='仓库位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='platform.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'tenant_warehouse',
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(verbose_name='当前库存')),
                ('safety', models.IntegerField(verbose_name='安全库存')),
                ('severity', models.CharField(choices=[('高', '高'), ('中', '中'), ('低', '低')], default='中', max_length=10, verbose_name='严重程度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='platform.tenant', verbose_name='所属租户')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tenant_db.product', verbose_name='商品')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tenant_db.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存预警',
                'verbose_name_plural': '库存预警',
                'db_table': 'tenant_inventory_alert',
            },
        ),
    ]
